language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - ./vendor/bin/phing
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
